### PR TITLE
Implement HEAD based on files in desired directory

### LINKED ISSUE #15: Implement HTTP `HEAD` support
Return HTTP `200` when client sends a `HEAD` request for a file in the directory specified by the `-d` option. Should pass cob_spec's [HEAD test](https://github.com/8thlight/cob_spec/tree/master/FitNesseRoot/HttpTestSuite/FileServerTestSuite/SimpleHead).

### PR DESCRIPTION
**Pull request by bgerstle**
> Resolves #15

- [x] Scope out classes for file-based `HttpResponder`
- [x] Test `FileHttpResponder` functionality with mocked `DataSource` (no real files)
- [x] Run integration test with generated files in tmp directory
- [x] Write an acceptance test which sends a request for a file (or just lean on cob_spec for that)

### CODE REVIEW

**Comment by bgerstle** [comment]
Some questions:

- Should there be separate `FileHttpResponder` instances for different kinds of requests? 
  - If so, am I to mock out every `File` interface that I use?
- If not, should the `FileHttpResponder` itself have different methods for each...method?
- Will all of this result in ravioli code?

**Comment by bgerstle** [comment]
💥 
image

**Comment by trptcolin** [comment]
To your questions:

> Should there be separate FileHttpResponder instances for different kinds of requests?
> If so, am I to mock out every File interface that I use?
> If not, should the FileHttpResponder itself have different methods for each...method?

I think there are lots of reasonable ways to design it, depending on what responsibility you think is core to a given object and how you find the requirements evolving. 

Perhaps there's one top-level object that delegates work to other classes based on the requests it gets (maybe based on HTTP method? maybe based on URL? maybe both) - kind of a "router" (e.g. [Rails](https://guides.rubyonrails.org/routing.html), [Express](https://expressjs.com/en/guide/routing.html)). Or perhaps all the objects sit as peers at the top level and get tried one after the other - more of a "middleware" approach ([Rack](https://rack.github.io/), [WSGI](http://wsgi.tutorial.codepoint.net/), [Plug](https://hexdocs.pm/plug/readme.html)). 

It looks like right now you've got a middleware-looking approach in place (`public boolean matches(Request request)` suggests that), which seems totally fine.

In general, I'd advocate for not trying to get it *right* - rather, get it working, and you can evolve it as your needs change. We're always learning about the systems we build, so the longer we can delay decisions or leave them open to reversal, the better decisions we end up with. Of course some bigger decisions have to be made early and are hard to change (e.g. language choice, seams between microservices) - but most of them can change pretty easily, especially for small systems.


> Will all of this result in ravioli code?

Heh, I've seen that term before but never understood it to be a negative thing, more in comparison to "spaghetti code". But in any case I think I understand the concern, that "ravioli code" might seem like a lot of ceremony and indirection, without discernible benefit. Yes, with mechanical application of things like the SOLID principles, that's possible. [We should talk about those soon.] There are tensions and tradeoffs between YAGNI/KISS, the [fourth rule of simple design](https://www.martinfowler.com/bliki/BeckDesignRules.html), and things like SOLID - so I don't tend to advocate for unthinking adherence to any of them. For the purposes of this project, I think we should be aiming for conversation and balance, with a bias towards decoupling by default - but only where that decoupling has a reasonable expectation of paying off.

**Comment by bgerstle** [comment]
That’s fine, there’s only supposed to be one match per request. That is,
order does not dictate precedence.

**Pull request merged**
